// Shapes © Freya Holmér - https://twitter.com/FreyaHolmer/
// Website & Documentation - https://acegikmo.com/shapes/

// Do not edit this manually, this file is automatically generated
// Please use the Shapes settings window instead

#define FRAG_OUTPUT_V4 half4
#define LOCAL_ANTI_ALIASING_QUALITY 2
#define QUAD_INTERPOLATION_QUALITY 1
#define NOOTS_ACROSS_SCREEN 100
